config/routes.rb
Rails.application.routes.draw do

  controller :currencies do
    get   '/'      => :index, :as => :currencies
    get   '/admin(/:code)' => :edit, :as => :edit_currency
    patch '/admin(/:code)' => :update, :as => :update_currency
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord
  after_commit :broadcast_change

  # only validates values that user can actually change
  validates :forced_val, numericality: { greater_than_or_equal_to: 0.01 }
  validate :forced_till_is_in_future

  # allows val to have spaces '1 000,50'
  # and ',' instead of '.'
  def forced_val=(val)
    if val.is_a? String
      val.gsub!(/\s+/, "")
      val.sub!(/,/, ".")
    end
    super(val)
  end

  # returns currency value fetched from it's source
  def fetch
    self.send(code + '_value')
  end

  # fetches currency value from it's source and updates the db
  def fetch!
    self.val = fetch
    self.last_updated = Time.zone.now
    self.save!
  end

  private
  # fetches exchange rate for the 'usd' currency from cbr.ru
  def usd_value
    # CBR.ru may not update exchange rate on holidays
    # so the we need the most recent exchange rate up to date.
    # It is assumed here that exchange rate is updated at least once a month
    Time.use_zone('Europe/Moscow') do
      today = Time.zone.now
      date1 = (today-1.month).strftime("%d/%m/%Y")
      date2 = today.strftime("%d/%m/%Y")
      url = "http://www.cbr.ru/scripts/XML_dynamic.asp?date_req1=#{date1}&date_req2=#{date2}&VAL_NM_RQ=R01235"
      begin
        page = Net::HTTP::get(URI(url))
        xml = Nokogiri::XML(page)
        val = xml.xpath('//ValCurs//Record//Value').last.content
        m = val.match(/(?<rubl>\d+)(.|,)(?<cop>\d+)/)
        BigDecimal("#{m[:rubl]}.#{m[:cop]}")
      rescue StandardError => error
        # rescuing StandardError is a bad practice
        # but for the sake of a simplification
        # we don't care here if it's a timeout, 503 or the response xml is malformed
        nil
      end
    end
  end

  # runs BroadcastChangeJob when a currency is updated 
  def broadcast_change
    # don't broadcast submits from /admin when nothing changed
      BroadcastChangeJob.perform_now(self) unless previous_changes.empty?
  end
  
  def forced_till_is_in_future
    if forced_till_changed? and (!forced_till or !(/#{FORM_VALIDATORS['date_rb']}/ =~ forced_till_before_type_cast))
      # datetime typecast will make date of everything (even a string with no digits) 
      # so we have to enforce datetime format
      errors.add(:forced_till, I18n.t("is not a valid time (date)")+" (#{forced_till_before_type_cast})") 
    elsif forced and forced_till < Time.zone.now
      # don't allow forced value to be set when the time for it to be reset
      # has already passed
      errors.add(:forced_till, I18n.t('time has already passed! Please choose time in the future.')) 
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/currencies_controller.rb
require 'net/http'

class CurrenciesController < ApplicationController
  around_action :use_users_timezone
  def index
    @any_update_failed = Currency.where(update_failed: true, forced: false).any?
    @currencies = Currency.all
    @currencies = [] if !@currencies 
  end

  def edit
    @curr = usd_or_param params
    @code = params_code params
  end

  def update
    # edit selected currency or usd if none selected
    @curr = usd_or_param params
    @curr.assign_attributes(curr_params)
    if @curr.valid?
      if !@curr.save
        flash.now[:danger] = 'Please try again later. If the problem persists please contact support.' 
      else
        # assign a new job
        if @curr.forced
          UnforceCurrencyJob.set(wait_until: @curr.forced_till).perform_later(@curr)
          flash[:success] = 'The currency value is forced.'
        else 
          flash[:warning] = 'Forced value is saved (enable to apply).'
        end
        # redirect to /admin if it was used to open edit page (no :code means usd is being edited)
        # else redirect to /admin/:code
        redirect_to edit_currency_path(params_code params)
      end
    else
      render 'edit'
    end
    
  end

  private 
  def curr_params
    params.require(:currency).permit(:code, :forced_val, :forced_till, :forced)
  end

  # returns :code from the request if there is one
  def params_code params
    params[:code] ? params[:code] : ''
  end

  # returns usd currency or currency with code from the request 
  def usd_or_param( params )
    curr_code = params[:code] ? params[:code] : 'usd'
    curr = Currency.where(code: curr_code).first  # doesn't allow SQL Injection
    raise ActiveRecord::RecordNotFound if !curr
    
    curr
  end

  # treat user's input with an appropriate tinezone setting
  def use_users_timezone
    timezone = Time.find_zone(cookies[:timezone]) or Time.zone
    Time.use_zone(timezone) { yield }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currency_helper.rb
module CurrencyHelper
  def localize_curr curr
    number_to_currency(curr, locale: locale, unit: '')
  end

  def update_failed curr
    curr.update_failed and !curr.forced
  end
end

app/views/currencies/edit.html.erb
<% content_for :title do
  t('Edit currency')
end %>

<% content_for :editor_css do
  stylesheet_link_tag 'edit'
end %>

<% content_for :editor_js do
  javascript_include_tag 'edit'
end %>

<% content_for :editor_js do
    javascript_include_tag 'vendor'
end %>

<%= render 'shared/messages' %>

<h1 class='title'> <%= t('Force currency value') %>  <strong> <%= @curr.code.upcase %> </strong> </h1>
<%= form_for @curr, url: update_currency_path(@code), 
                    html: {class: 'currency-form', 
                           id: 'currency-form'} do |c| %> 
    <div>
        <%= c.label :forced_val, t('Forced value') %>
        <%= c.text_field :forced_val, placeholder: '10,00', class: "text-input", 
            value: localize_curr(@curr.errors.include?(:forced_val) ? @curr.forced_val_before_type_cast : @curr.forced_val),
            required: true,
            'data-parsley-pattern' => FORM_VALIDATORS['currency_js'],
            'data-parsley-pattern-message' => t('Please enter a number, eg 123,45')
        %>
    </div>
    <div>
        <%= c.label :forced_till, t('Force untill')%> 
        <%= c.text_field :forced_till, placeholder: '31.12.2016 10:00', class: "text-input", 
            value: @curr.errors.include?(:forced_till) ? @curr.forced_till_before_type_cast : @curr.forced_till.strftime('%d.%m.%Y   %H:%M:%S'),
            required: true,
            'data-parsley-pattern' => FORM_VALIDATORS['date_js'],
            'data-parsley-pattern-message' => t('Expected format is: dd/mm/yyyy  hh:mm[:ss]')
        %>
    </div>
    <div>
        <%= c.check_box :forced, class: 'toggle', id: 'currency_forced' %>
        <label for='currency_forced' data-on="<%= t('Enabled') %>" data-off="<%= t('Disabled') %>" id='currency_forced_label'></label>
    </div>
  <div class="button-group">
        <%= c.submit t('Save'), class: 'button save-button' %><!--
     --><%= link_to t('Home'), :currencies, class: 'button return-button'%>
  </div>
<% end %> 

app/views/currencies/index.html.erb
<% content_for :title do
    t('Currency exchange rate')
end %>

<% content_for :index_css do
    stylesheet_link_tag 'index'
end %>

<main>
  <h1> <%= t('Currency exchange rate') %> </h1>
  <% cache @currencies do %>
    <table class='currencies table-hover'> 
    <thead>
      <tr>
        <th><%= t('Code') %></th>
        <th><%= t('Description') %></th>
        <th><%= t('CBR exchange rate')%></th>
        <th></th>
      </tr>
    </thead>
      <tbody>
        <% @currencies.each do |curr| %>
          <tr>
            <% cache curr do %>
            
              <td <% if update_failed curr %> class = 'update-failed' <% end %> >
                <%= curr.code.upcase %>
              </td>

              <td> <%= t(curr.description) %> </td>
              
              <td id = <%= curr.code %> class = 'currency'> 
                <%= render 'shared/currency', curr: curr %> 
              </td>

              <td> <%= link_to t('Edit'), edit_currency_path(curr.code) %> </td>

            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
   
      <p class = 'update-failed  <% unless @any_update_failed %> hidden <% end %>' id='update-failed-notice'> 
        <%= t('Exchange rate may be outdated for this currency') %> 
      </p>
   
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield :title %> </title>
    <meta charset='UTF-8'>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' %>
    <%= yield :editor_css %>
    <%= yield :index_css %>
    <%= action_cable_meta_tag %>
    <%= javascript_include_tag 'application'%>
    <%= yield :editor_js %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_currency.html.erb
1<%= t(curr.code) %> = <%= localize_curr(curr.forced ? curr.forced_val : curr.val)  %> <%= t('RUB') %>

app/views/shared/_messages.html.erb
<% if @curr.errors.any? %>
  <% @curr.errors.full_messages.each do |msg| %>
    <div class='alert alert-danger'> 
      <div class='fixed-width'>
        <strong><%= t('Error') %>!</strong> 
        <%= msg %> 
      </div>
    </div>
  <% end %>
<% end %>

<% if flash.any? %>
  <% flash.each do |status, msg| %>
    <div class="alert alert-<%= status %>"> 
      <div class='fixed-width'>
        <%= t(msg) %> 
      </div>
    </div>
  <% end %>
<% end %>